CHANGELOG.md

Only updating changelog (and not versions.txt)

Prepare for 1.0.9-rc3 release

---

CHANGELOG.md

Correct month of release in Changelog.md

---

CHANGELOG.md

Prepare for 1.0.9-rc4 release

---

CHANGELOG.md

Prepare for 1.0.8.5 release

---

CHANGELOG.md

add release note for 1.0.9-rc6

add release note for 1.0.9-rc6

---

LICENSE

Updates to the license for IoT Edge including clarifications on the distribution rights.

Update IoT Edge license to be more permissive

---

latest-versions.json

Update latest version to 1.0.9.5

Update latest version to 1.0.9.5

---

latest-versions.json

Update latest version to 1.0.10

Update latest version to 1.0.10

---

latest-versions.json

Update latest-versions for release1.0.10.3

Update latest-versions for release1.0.10.3

---

CHANGELOG.md

Update latest version to 1.2.0-rc3

Update latest version to 1.2.0-rc3

---

latest-versions.json

Update latest version to 1.1.1

Update latest version to 1.1.1

---

latest-iotedge-lts.json

Update latest version to 1.1.2

Update latest version to 1.1.2

---

latest-iotedge-lts.json

Update the latest version to 1.1.3

Update the latest version to 1.1.3

---

latest-aziot-edge.json

Update the latest version to 1.2.1

---

latest-aziot-edge.json
latest-aziot-identity-service.json

aziot-edge 1.2.2
aziot-identity-service 1.2.1

Update the latest version

---

latest-aziot-edge.json
latest-aziot-identity-service.json

aziot-edge 1.2.3
aziot-identity-service 1.2.2

Update the latest versions

---

latest-iotedge-lts.json

Update the latest version to 1.1.4

Update the latest version to 1.1.4

---

tools/ReleaseProcess/UploadArtifactsToGitHub.ps1

Update tools/ReleaseProcess/UploadArtifactsToGitHub.ps1 to work better with release/1.1 branch

Update UploadArtifactsToGitHub for release/1.1 branch.

---

latest-iotedge-lts.json

Update the latest version to 1.1.5

Update the latest version to 1.1.5

---

latest-iotedge-lts.json

Prepare for release 1.1.6

---

latest-aziot-edge.json
latest-aziot-identity-service.json

Update the latest version to 1.2.4

Update the latest version to 1.2.4

---

latest-iotedge-lts.json

Prepare for release 1.1.8

---

latest-aziot-edge.json
latest-aziot-identity-service.json

Prepare for Release 1.2.5

---

latest-aziot-edge.json
latest-aziot-identity-service.json

Prepare For Release 1.2.7

---

latest-iotedge-lts.json

Prepare for release 1.1.9

---

latest-aziot-edge.json
latest-aziot-identity-service.json

Prepare for release 1.2.8
- aziot-edge 1.2.8
- aziot-identity-service 1.2.6

Prepare for release 1.2.8

---

latest-iotedge-lts.json

Prepare for release 1.1.11

---

latest-iotedge-lts.json

Prepare for Release 1.1.12

---

latest-aziot-edge.json

Prepare the release 1.2.9

---

latest-iotedge-lts.json

Update latest-iotedge-lts.json for iotedge v1.1.13

Prepare for release 1.1.13

---

latest-aziot-edge.json

Bump latest aziot-edge version.

Prepare for 1.2.10 release

---

latest-iotedge-lts.json

Update EdgeAgent & EdgeHub version to 1.1.14

Base image update release 1.1.14

---

latest-aziot-edge.json
latest-aziot-identity-service.json

Prepare for Release 1.3.0

---

latest-aziot-edge.json
latest-aziot-identity-service.json

This reverts commit ca1cdc40f84c34cb707a1f5acca4b4769b5033be.

Revert "Prepare for Release 1.3.0 (#97)"

---

latest-aziot-edge.json
latest-aziot-identity-service.json

Prepare for release 1.4.0

---

README.md

Update description of what data is collected and how to opt-out.

Update data collection info

---

latest-iotedge-lts.json

Update latest LTS version to 1.4.0

Update latest LTS version to 1.4.0
